import { z } from "zod";
import { withDatabaseClient,withTransaction } from "@/lib/db/client";
import { appendDomainEvent } from "@/lib/events/outbox";
const createInput=z.object({name:z.string().trim().min(2).max(120),subject:z.string().trim().min(2).max(200),body:z.string().trim().min(5).max(5000)});
export async function createCampaign(actorId:string,raw:unknown){const input=createInput.parse(raw);return withDatabaseClient(async client=>(await client.execute<{public_id:string}>("INSERT INTO notification_campaign(name,subject,body,status,created_by) VALUES($1,$2,$3,'DRAFT',$4) RETURNING public_id",[input.name,input.subject,input.body,actorId])).rows[0]);}
export async function previewCampaign(publicId:string){return withDatabaseClient(async client=>{const row=(await client.execute("UPDATE notification_campaign SET status='PREVIEWED',updated_at=now() WHERE public_id=$1 AND status IN('DRAFT','PREVIEWED') RETURNING public_id,name,subject,body,status",[publicId])).rows[0];if(!row)throw new Error("CAMPAIGN_NOT_PREVIEWABLE");return row;});}
export async function scheduleCampaign(publicId:string,scheduledAt:Date){return withTransaction(async client=>{const campaign=(await client.execute<{id:string}>("UPDATE notification_campaign SET status='SCHEDULED',scheduled_at=$2,updated_at=now() WHERE public_id=$1 AND status IN('DRAFT','PREVIEWED','PAUSED') RETURNING id",[publicId,scheduledAt])).rows[0];if(!campaign)throw new Error("CAMPAIGN_NOT_SCHEDULABLE");await client.execute(`INSERT INTO campaign_recipient(campaign_id,account_id) SELECT $1,account_id FROM marketing_subscription WHERE status='SUBSCRIBED' ON CONFLICT DO NOTHING`,[campaign.id]);return{publicId,status:"SCHEDULED" as const};});}
export async function updateCampaignStatus(publicId:string,status:"PAUSED"|"CANCELLED"){return withDatabaseClient(async client=>{const row=(await client.execute("UPDATE notification_campaign SET status=$2,updated_at=now() WHERE public_id=$1 AND status IN('SCHEDULED','ACTIVE','PAUSED') RETURNING public_id,status",[publicId,status])).rows[0];if(!row)throw new Error("CAMPAIGN_STATUS_INVALID");return row;});}
export async function dispatchDueCampaigns(){return withTransaction(async client=>{const campaigns=await client.execute<{id:string;subject:string;body:string}>("UPDATE notification_campaign SET status='ACTIVE',updated_at=now() WHERE status='SCHEDULED' AND scheduled_at<=now() RETURNING id,subject,body");let queued=0;for(const campaign of campaigns.rows){const recipients=await client.execute<{account_id:string}>("SELECT account_id FROM campaign_recipient WHERE campaign_id=$1 AND status='SNAPSHOT' FOR UPDATE",[campaign.id]);for(const recipient of recipients.rows){const eventId=await appendDomainEvent(client,{eventType:"marketing.campaign.v1",aggregateType:"notification_campaign",aggregateId:campaign.id,payload:{accountId:recipient.account_id,campaignSubject:campaign.subject,campaignBody:campaign.body}});await client.execute("UPDATE campaign_recipient SET status='QUEUED',event_id=$3,updated_at=now() WHERE campaign_id=$1 AND account_id=$2",[campaign.id,recipient.account_id,eventId]);queued+=1;}await client.execute("UPDATE notification_campaign SET status='COMPLETED',updated_at=now() WHERE id=$1",[campaign.id]);}return{campaigns:campaigns.rowCount,queued};});}
export async function listCampaigns(){return withDatabaseClient(async client=>(await client.execute(`SELECT campaign.public_id,campaign.name,campaign.subject,campaign.body,campaign.status,campaign.scheduled_at,count(recipient.account_id)::int AS recipients,count(*) FILTER(WHERE recipient.status='SUPPRESSED')::int AS suppressed FROM notification_campaign campaign LEFT JOIN campaign_recipient recipient ON recipient.campaign_id=campaign.id GROUP BY campaign.id ORDER BY campaign.updated_at DESC`)).rows);}
