import type { DatabaseClient } from "@/lib/db/client";
import { withTransaction } from "@/lib/db/client";
import { appendDomainEvent } from "@/lib/events/outbox";

export function isAvailabilityTransition(beforeAvailable:number,afterAvailable:number){return beforeAvailable<=0&&afterAvailable>0;}

export async function subscribeNewsletter(accountId:string,source:string){return withTransaction(async client=>{await client.execute(`INSERT INTO marketing_subscription(account_id,status,consent_source,consented_at,unsubscribed_at) VALUES($1,'SUBSCRIBED',$2,now(),NULL) ON CONFLICT(account_id) DO UPDATE SET status='SUBSCRIBED',consent_source=EXCLUDED.consent_source,consented_at=now(),unsubscribed_at=NULL,updated_at=now()`,[accountId,source]);await client.execute("INSERT INTO consent_event(account_id,purpose,channel,granted,affirmative_action) VALUES($1,'MARKETING_EMAIL','EMAIL',true,$2)",[accountId,source]);return{status:"SUBSCRIBED" as const};});}
export async function unsubscribeNewsletter(accountId:string){return withTransaction(async client=>{await client.execute("UPDATE marketing_subscription SET status='UNSUBSCRIBED',unsubscribed_at=now(),updated_at=now() WHERE account_id=$1",[accountId]);await client.execute("INSERT INTO consent_event(account_id,purpose,channel,granted,affirmative_action) VALUES($1,'MARKETING_EMAIL','EMAIL',false,'ACCOUNT_UNSUBSCRIBE')",[accountId]);return{status:"UNSUBSCRIBED" as const};});}
export async function subscribeRestock(accountId:string,variantId:string){return withTransaction(async client=>{const variant=await client.execute<{available:number}>("SELECT balance.on_hand-balance.reserved AS available FROM product_variant variant JOIN inventory_balance balance ON balance.variant_id=variant.id WHERE variant.id=$1 AND variant.enabled AND variant.purchasable",[variantId]);if(!variant.rows[0])throw new Error("VARIANT_NOT_FOUND");if(variant.rows[0].available>0)throw new Error("VARIANT_ALREADY_AVAILABLE");await client.execute(`INSERT INTO restock_subscription(account_id,variant_id,status,subscribed_at,completed_at) VALUES($1,$2,'ACTIVE',now(),NULL) ON CONFLICT(account_id,variant_id) DO UPDATE SET status='ACTIVE',subscribed_at=now(),completed_at=NULL`,[accountId,variantId]);return{status:"ACTIVE" as const};});}
export async function unsubscribeRestock(accountId:string,variantId:string){return withTransaction(async client=>{await client.execute("UPDATE restock_subscription SET status='UNSUBSCRIBED' WHERE account_id=$1 AND variant_id=$2 AND status='ACTIVE'",[accountId,variantId]);return{status:"UNSUBSCRIBED" as const};});}
export async function completeRestockSubscriptions(client:DatabaseClient,variantId:string){const subscriptions=await client.execute<{id:string;account_id:string}>("UPDATE restock_subscription SET status='COMPLETED',completed_at=now() WHERE variant_id=$1 AND status='ACTIVE' RETURNING id,account_id",[variantId]);for(const subscription of subscriptions.rows)await appendDomainEvent(client,{eventType:"inventory.variant.restocked.v1",aggregateType:"restock_subscription",aggregateId:subscription.id,payload:{accountId:subscription.account_id,variantId}});return subscriptions.rowCount;}
