import { createHash, timingSafeEqual } from "node:crypto";
import { z } from "zod";
import { getRuntimeConfig } from "@/lib/config/env";

const APS_HOSTED = { sandbox: "https://sbcheckout.payfort.com/FortAPI/paymentPage", production: "https://checkout.payfort.com/FortAPI/paymentPage" } as const;
const APS_API = { sandbox: "https://sbpaymentservices.payfort.com/FortAPI/paymentApi", production: "https://paymentservices.payfort.com/FortAPI/paymentApi" } as const;
type ApsValue = string | number | null | undefined;
type ApsParameters = Record<string, ApsValue>;
const responseParameters = z.record(z.string(), z.union([z.string(), z.number()]));

export type ProviderWebhook = { eventId:string; eventType:"PAYMENT_STATUS"|"REFUND_STATUS"; reference:string; status:"PENDING"|"CONFIRMED"|"FAILED"|"UNKNOWN"|"REFUNDED"; amountFils:number; currency:"JOD"; evidence:Record<string,unknown> };

function credentials(){const config=getRuntimeConfig();if(!config.APS_ACCESS_CODE||!config.APS_MERCHANT_IDENTIFIER||!config.APS_SHA_REQUEST_PHRASE||!config.APS_SHA_RESPONSE_PHRASE)throw new Error("AMAZON_PAYMENT_SERVICES_UNCONFIGURED");return{accessCode:config.APS_ACCESS_CODE,merchantIdentifier:config.APS_MERCHANT_IDENTIFIER,requestPhrase:config.APS_SHA_REQUEST_PHRASE,responsePhrase:config.APS_SHA_RESPONSE_PHRASE,environment:config.APS_ENVIRONMENT};}

export function calculateApsSignature(parameters:ApsParameters,phrase:string):string{const body=Object.entries(parameters).filter(([key,value])=>key!=="signature"&&value!==null&&value!==undefined).sort(([left],[right])=>left<right?-1:left>right?1:0).map(([key,value])=>`${key}=${String(value)}`).join("");return createHash("sha256").update(`${phrase}${body}${phrase}`,"utf8").digest("hex");}
function safeEqual(left:string,right:string){const expected=Buffer.from(left.toLowerCase(),"utf8");const actual=Buffer.from(right.toLowerCase(),"utf8");return expected.length===actual.length&&timingSafeEqual(expected,actual);}
function validateJodCardAmount(amountFils:number){if(!Number.isSafeInteger(amountFils)||amountFils<=0||amountFils>9_999_999_999)throw new Error("CARD_AMOUNT_INVALID");if(amountFils%10!==0)throw new Error("CARD_AMOUNT_REQUIRES_TEN_FILS_PRECISION");}
function isSimulation(){const config=getRuntimeConfig();return config.SIM_MODE||config.APP_ENV==="test";}

export async function createHostedPayment(input:{operationKey:string;amountFils:number;returnUrl:string;purpose:"ORDER";entityReference:string;customerEmail:string}){
  validateJodCardAmount(input.amountFils);
  if(isSimulation()){const reference=`sim_${input.entityReference}`;return{reference,hostedUrl:new URL("/api/v1/payments/simulate",getRuntimeConfig().STOREFRONT_ORIGIN).toString(),formFields:{merchant_reference:reference,amount:String(input.amountFils),outcome:"success",return_url:input.returnUrl},status:"PENDING" as const,expiresAt:new Date(Date.now()+15*60*1000).toISOString()};}
  const aps=credentials();const fields:Record<string,string>={command:"PURCHASE",access_code:aps.accessCode,merchant_identifier:aps.merchantIdentifier,merchant_reference:input.entityReference,amount:String(input.amountFils),currency:"JOD",language:"en",customer_email:input.customerEmail,return_url:input.returnUrl};fields.signature=calculateApsSignature(fields,aps.requestPhrase);return{reference:input.entityReference,hostedUrl:APS_HOSTED[aps.environment],formFields:fields,status:"PENDING" as const,expiresAt:new Date(Date.now()+15*60*1000).toISOString()};
}

function normalizeResponse(parameters:Record<string,string|number>):ProviderWebhook{const reference=String(parameters.merchant_reference??"");const amountFils=Number(parameters.amount);if(!reference||!Number.isSafeInteger(amountFils)||String(parameters.currency)!=="JOD")throw new Error("APS_RESPONSE_INVALID");const command=String(parameters.command??parameters.query_command??"");const code=String(parameters.transaction_code??parameters.response_code??"");const isRefund=command==="REFUND";const confirmed=isRefund?code==="06000":code==="14000";const pending=!code||["01","02","03","04","19"].includes(String(parameters.status??""));const providerId=String(parameters.fort_id??reference);return{eventId:`${providerId}:${command||"STATUS"}:${code||String(parameters.status??"UNKNOWN")}`,eventType:isRefund?"REFUND_STATUS":"PAYMENT_STATUS",reference,status:confirmed?(isRefund?"REFUNDED":"CONFIRMED"):pending?"PENDING":"FAILED",amountFils,currency:"JOD",evidence:{fortId:parameters.fort_id,responseCode:parameters.response_code,transactionCode:parameters.transaction_code,status:parameters.status,transactionStatus:parameters.transaction_status,paymentOption:parameters.payment_option,authorizationCode:parameters.authorization_code}};}

export function verifyApsResponse(parameters:Record<string,string|number>):ProviderWebhook{const parsed=responseParameters.parse(parameters);const signature=String(parsed.signature??"");const aps=credentials();if(!signature||String(parsed.access_code??"")!==aps.accessCode||String(parsed.merchant_identifier??"")!==aps.merchantIdentifier)throw new Error("APS_RESPONSE_SIGNATURE_INVALID");if(!safeEqual(calculateApsSignature(parsed,aps.responsePhrase),signature))throw new Error("APS_RESPONSE_SIGNATURE_INVALID");return normalizeResponse(parsed);}
export function verifyProviderWebhook(rawBody:string):ProviderWebhook{return verifyApsResponse(responseParameters.parse(JSON.parse(rawBody) as unknown));}

async function apsJsonRequest(parameters:Record<string,string>):Promise<Record<string,string|number>>{const aps=credentials();const signed={...parameters,signature:calculateApsSignature(parameters,aps.requestPhrase)};const response=await fetch(APS_API[aps.environment],{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(signed),signal:AbortSignal.timeout(12_000)});if(!response.ok)throw new Error(response.status>=500||response.status===429?"AMAZON_PAYMENT_SERVICES_UNAVAILABLE":"AMAZON_PAYMENT_SERVICES_REJECTED");const parsed=responseParameters.parse(await response.json());verifyApsResponse(parsed);return parsed;}
export async function queryHostedPayment(reference:string){if(isSimulation())return{reference,status:"PENDING" as const,amountFils:0,currency:"JOD" as const,evidence:{source:"simulation"}};const aps=credentials();return normalizeResponse(await apsJsonRequest({query_command:"CHECK_STATUS",access_code:aps.accessCode,merchant_identifier:aps.merchantIdentifier,merchant_reference:reference,language:"en"}));}
export async function executeProviderRefund(input:{operationKey:string;paymentReference:string;amountFils:number}){validateJodCardAmount(input.amountFils);const maintenanceReference=`REF-${input.operationKey.replace(/[^A-Za-z0-9_.-]/g,"-")}`.slice(0,40);if(isSimulation())return{reference:maintenanceReference,status:"CONFIRMED" as const};const aps=credentials();const response=await apsJsonRequest({command:"REFUND",access_code:aps.accessCode,merchant_identifier:aps.merchantIdentifier,merchant_reference:input.paymentReference,maintenance_reference:maintenanceReference,amount:String(input.amountFils),currency:"JOD",language:"en"});return{reference:String(response.maintenance_reference??maintenanceReference),status:String(response.response_code)==="06000"?"CONFIRMED" as const:"FAILED" as const};}
