import{randomInt}from"node:crypto";
import{hash,verify}from"@node-rs/argon2";
import{generateAuthenticationOptions,generateRegistrationOptions,verifyAuthenticationResponse,verifyRegistrationResponse,type AuthenticationResponseJSON,type RegistrationResponseJSON}from"@simplewebauthn/server";
import{withDatabaseClient,withTransaction}from"@/lib/db/client";
import{getRuntimeConfig}from"@/lib/config/env";
import{generateRecoveryPassphrase,hashToken}from"@/lib/security/crypto";
import{appendAudit}from"@/lib/audit/service";
import{queueSecureDelivery}from"@/lib/notifications/secure-delivery";

async function setupAccount(token:string){return withDatabaseClient(async client=>{const result=await client.query<{account_id:string;email_normalized:string;display_name:string}>(`SELECT auth.account_id,account.email_normalized,account.display_name FROM auth_token AS auth JOIN account ON account.id=auth.account_id JOIN staff_account AS staff ON staff.account_id=account.id AND staff.role_id='CTO' WHERE auth.purpose='CTO_SETUP' AND auth.verifier_hash=$1 AND auth.consumed_at IS NULL AND auth.superseded_at IS NULL AND auth.expires_at>now()`,[hashToken(token)]);if(!result.rows[0])throw new Error("SETUP_TOKEN_INVALID");return result.rows[0];});}

export async function generateCtoRecoverySecret(token:string){const account=await setupAccount(token);const secret=generateRecoveryPassphrase();const verifierHash=await hash(secret,{memoryCost:19456,timeCost:2,parallelism:1});await withDatabaseClient(client=>client.query("INSERT INTO pending_recovery_secret(account_id,verifier_hash,expires_at) VALUES($1,$2,now()+interval '30 minutes') ON CONFLICT(account_id) DO UPDATE SET verifier_hash=EXCLUDED.verifier_hash,failed_attempts=0,expires_at=EXCLUDED.expires_at,created_at=now()",[account.account_id,verifierHash]).then(()=>undefined));return{recoverySecret:secret};}

export async function beginCtoKeyRegistration(token:string){const account=await setupAccount(token);const config=getRuntimeConfig();const existing=await withDatabaseClient(async client=>(await client.query<{id:string}>("SELECT id FROM webauthn_credential WHERE account_id=$1",[account.account_id])).rows);const options=await generateRegistrationOptions({rpName:config.WEBAUTHN_RP_NAME,rpID:config.WEBAUTHN_RP_ID,userID:new TextEncoder().encode(account.account_id),userName:account.email_normalized,userDisplayName:account.display_name,attestationType:"none",excludeCredentials:existing.map(item=>({id:item.id})),authenticatorSelection:{residentKey:"preferred",userVerification:"required"}});await withDatabaseClient(client=>client.query("INSERT INTO webauthn_challenge(account_id,ceremony,challenge,expires_at) VALUES($1,'REGISTRATION',$2,now()+interval '5 minutes')",[account.account_id,options.challenge]).then(()=>undefined));return options;}

export async function finishCtoKeyRegistration(token:string,response:RegistrationResponseJSON,label:string,independentKeyAcknowledged:boolean){const account=await setupAccount(token);if(!independentKeyAcknowledged)throw new Error("INDEPENDENT_KEY_ACKNOWLEDGMENT_REQUIRED");const config=getRuntimeConfig();return withTransaction(async client=>{const challenge=await client.query<{id:string;challenge:string}>("SELECT id,challenge FROM webauthn_challenge WHERE account_id=$1 AND ceremony='REGISTRATION' AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1 FOR UPDATE",[account.account_id]);if(!challenge.rows[0])throw new Error("CHALLENGE_INVALID");const verification=await verifyRegistrationResponse({response,expectedChallenge:challenge.rows[0].challenge,expectedOrigin:[config.STOREFRONT_ORIGIN,config.ADMIN_ORIGIN],expectedRPID:config.WEBAUTHN_RP_ID,requireUserVerification:true});if(!verification.verified||!verification.registrationInfo)throw new Error("WEBAUTHN_INVALID");const credential=verification.registrationInfo.credential;await client.query("INSERT INTO webauthn_credential(id,account_id,public_key,counter,transports,device_label,independent_key) VALUES($1,$2,$3,$4,$5,$6,true)",[credential.id,account.account_id,Buffer.from(credential.publicKey),credential.counter,credential.transports??[],label.slice(0,100)]);await client.query("UPDATE webauthn_challenge SET consumed_at=now() WHERE id=$1",[challenge.rows[0].id]);await appendAudit(client,{actorId:account.account_id,actorRole:"CTO",action:"security_key.registered",targetType:"webauthn_credential",targetId:credential.id,domain:"security",sensitive:true});return{registered:true};});}

export async function beginCtoKeyAssertion(token:string){const account=await setupAccount(token);const config=getRuntimeConfig();return withTransaction(async client=>{const credentials=await client.query<{id:string}>("SELECT id FROM webauthn_credential WHERE account_id=$1 AND independent_key=true",[account.account_id]);if(!credentials.rowCount)throw new Error("NO_KEY_REGISTERED");const options=await generateAuthenticationOptions({rpID:config.WEBAUTHN_RP_ID,userVerification:"required",allowCredentials:credentials.rows.map(item=>({id:item.id}))});await client.query("INSERT INTO webauthn_challenge(account_id,ceremony,challenge,expires_at) VALUES($1,'AUTHENTICATION',$2,now()+interval '5 minutes')",[account.account_id,options.challenge]);return options;});}

export async function finishCtoKeyAssertion(token:string,response:AuthenticationResponseJSON){const account=await setupAccount(token);const config=getRuntimeConfig();return withTransaction(async client=>{const challenge=await client.query<{id:string;challenge:string}>("SELECT id,challenge FROM webauthn_challenge WHERE account_id=$1 AND ceremony='AUTHENTICATION' AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1 FOR UPDATE",[account.account_id]);if(!challenge.rows[0])throw new Error("CHALLENGE_INVALID");const stored=await client.query<{id:string;public_key:Uint8Array;counter:number;transports:string[]}>("SELECT id,public_key,counter,transports FROM webauthn_credential WHERE account_id=$1 AND id=$2 AND independent_key=true FOR UPDATE",[account.account_id,response.id]);if(!stored.rows[0])throw new Error("WEBAUTHN_INVALID");const credential=stored.rows[0];const transports=credential.transports.filter((item):item is "ble"|"hybrid"|"internal"|"nfc"|"usb"=>["ble","hybrid","internal","nfc","usb"].includes(item));const result=await verifyAuthenticationResponse({response,expectedChallenge:challenge.rows[0].challenge,expectedOrigin:[config.STOREFRONT_ORIGIN,config.ADMIN_ORIGIN],expectedRPID:config.WEBAUTHN_RP_ID,credential:{id:credential.id,publicKey:Uint8Array.from(credential.public_key),counter:credential.counter,transports},requireUserVerification:true});if(!result.verified)throw new Error("WEBAUTHN_INVALID");await client.query("UPDATE webauthn_challenge SET consumed_at=now() WHERE id=$1",[challenge.rows[0].id]);await client.query("UPDATE webauthn_credential SET counter=$2,last_used_at=now() WHERE id=$1",[credential.id,result.authenticationInfo.newCounter]);await appendAudit(client,{actorId:account.account_id,actorRole:"CTO",action:"security_key.onboarding_asserted",targetType:"webauthn_credential",targetId:credential.id,domain:"security",sensitive:true});return{asserted:true,credentialId:credential.id};});}

export async function issueSetupContactCode(token:string,channel:"EMAIL"|"PHONE",phone?:string){const account=await setupAccount(token);if(channel==="PHONE"&&!/^\+962[0-9]{8,9}$/.test(phone??""))throw new Error("PHONE_INVALID");const code=String(randomInt(100000,1000000));const destination=channel==="EMAIL"?account.email_normalized:phone;if(!destination)throw new Error("CONTACT_DESTINATION_REQUIRED");await withTransaction(async client=>{const purpose=channel==="EMAIL"?"EMAIL_VERIFY":"PHONE_VERIFY";await client.query("UPDATE auth_token SET superseded_at=now() WHERE account_id=$1 AND purpose=$2 AND consumed_at IS NULL AND superseded_at IS NULL",[account.account_id,purpose]);await client.query("INSERT INTO auth_token(account_id,purpose,verifier_hash,expires_at) VALUES($1,$2,$3,now()+interval '5 minutes')",[account.account_id,purpose,hashToken(code)]);if(channel==="PHONE")await client.query("UPDATE account SET phone_e164=$2,phone_verified_at=NULL WHERE id=$1",[account.account_id,phone]);await queueSecureDelivery(client,{eventType:"security.cto.setup_contact.v1",aggregateType:"account",aggregateId:account.account_id,accountId:account.account_id,channel,destination,token:code,expiresAt:new Date(Date.now()+5*60*1000)});});return{sent:true,developmentCode:["local","test"].includes(getRuntimeConfig().APP_ENV)?code:undefined};}

export async function confirmSetupContactCode(token:string,channel:"EMAIL"|"PHONE",code:string){const account=await setupAccount(token);return withTransaction(async client=>{const purpose=channel==="EMAIL"?"EMAIL_VERIFY":"PHONE_VERIFY";const proof=await client.query<{id:string}>("SELECT id FROM auth_token WHERE account_id=$1 AND purpose=$2 AND verifier_hash=$3 AND consumed_at IS NULL AND superseded_at IS NULL AND expires_at>now() FOR UPDATE",[account.account_id,purpose,hashToken(code)]);if(!proof.rows[0])throw new Error("CONTACT_CODE_INVALID");await client.query("UPDATE auth_token SET consumed_at=now() WHERE id=$1",[proof.rows[0].id]);await client.query(channel==="EMAIL"?"UPDATE account SET email_verified_at=now() WHERE id=$1":"UPDATE account SET phone_verified_at=now() WHERE id=$1",[account.account_id]);return{verified:true};});}

export async function completeCtoSetup(token:string,input:{password:string;recoverySecret?:string;recoverySecretConfirmation:string;savedCopyAcknowledged:boolean}){if(input.password.length<12||input.recoverySecretConfirmation.trim().split(/\s+/).length!==12||!input.savedCopyAcknowledged)throw new Error("SETUP_REQUIREMENTS_INCOMPLETE");const account=await setupAccount(token);const pending=await withDatabaseClient(async client=>(await client.query<{verifier_hash:string;failed_attempts:number}>("SELECT verifier_hash,failed_attempts FROM pending_recovery_secret WHERE account_id=$1 AND expires_at>now()",[account.account_id])).rows[0]);if(!pending||pending.failed_attempts>=5||!await verify(pending.verifier_hash,input.recoverySecretConfirmation)){await withDatabaseClient(client=>client.query("UPDATE pending_recovery_secret SET failed_attempts=failed_attempts+1 WHERE account_id=$1",[account.account_id]).then(()=>undefined));throw new Error("SAVED_PASSPHRASE_CHECK_FAILED");}const passwordHash=await hash(input.password,{memoryCost:19456,timeCost:2,parallelism:1});return withTransaction(async client=>{const keys=await client.query("SELECT id FROM webauthn_credential WHERE account_id=$1 AND independent_key=true AND last_used_at IS NOT NULL FOR SHARE",[account.account_id]);if((keys.rowCount??0)<2)throw new Error("TWO_ASSERTED_INDEPENDENT_KEYS_REQUIRED");const contacts=await client.query<{email_verified_at:Date|null;phone_verified_at:Date|null}>("SELECT email_verified_at,phone_verified_at FROM account WHERE id=$1 FOR UPDATE",[account.account_id]);if(!contacts.rows[0]?.email_verified_at||!contacts.rows[0]?.phone_verified_at)throw new Error("CONTACT_VERIFICATION_REQUIRED");await client.query("UPDATE account SET password_hash=$2,status='ACTIVE',password_changed_at=now(),updated_at=now() WHERE id=$1",[account.account_id,passwordHash]);await client.query("UPDATE staff_account SET status='ACTIVE',mfa_completed_at=now() WHERE account_id=$1",[account.account_id]);await client.query("INSERT INTO recovery_secret(account_id,verifier_hash,saved_check_at) VALUES($1,$2,now())",[account.account_id,pending.verifier_hash]);await client.query("DELETE FROM pending_recovery_secret WHERE account_id=$1",[account.account_id]);await client.query("UPDATE auth_token SET consumed_at=now() WHERE purpose='CTO_SETUP' AND account_id=$1",[account.account_id]);await client.query("UPDATE platform_state SET cto_initialized_at=now(),updated_at=now() WHERE singleton=true");await appendAudit(client,{actorId:account.account_id,actorRole:"CTO",action:"cto.setup.completed",targetType:"account",targetId:account.account_id,domain:"security",sensitive:true});return{completed:true};});}
