export function codDeliveryFee(originalFeeFils:number,attemptsMade:number,reviewedThirdAttemptFeeFils=2000):number{if(!Number.isInteger(originalFeeFils)||originalFeeFils<0||!Number.isInteger(reviewedThirdAttemptFeeFils)||reviewedThirdAttemptFeeFils<0)throw new Error('FEE_INVALID');if(!Number.isInteger(attemptsMade)||attemptsMade<1||attemptsMade>3)throw new Error('ATTEMPT_INVALID');return attemptsMade===3?originalFeeFils+reviewedThirdAttemptFeeFils:originalFeeFils;}
export function canCustomerCancel(fulfillment:string):boolean{return ['UNFULFILLED','PROCESSING'].includes(fulfillment);}
export function damageClaimEligible(deliveredAt:Date,now:Date):boolean{const elapsed=now.getTime()-deliveredAt.getTime();return elapsed>=0&&elapsed<=7*86400000;}
export type RecoveryStep='CAPTCHA'|'EMAIL_OTP'|'PASSPHRASE'|'PHONE_OTP'|'WEBAUTHN'|'COMPLETE';
const recoverySteps:RecoveryStep[]=['CAPTCHA','EMAIL_OTP','PASSPHRASE','PHONE_OTP','WEBAUTHN','COMPLETE'];
export function advanceRecovery(current:RecoveryStep,proof:Exclude<RecoveryStep,'COMPLETE'>,startedAt:Date,now:Date):RecoveryStep{if(now.getTime()-startedAt.getTime()>=30*60*1000)throw new Error('RECOVERY_EXPIRED');if(current!==proof)throw new Error('RECOVERY_STEP_OUT_OF_ORDER');return recoverySteps[recoverySteps.indexOf(current)+1];}
export function otpValid(issuedAt:Date,now:Date,consumed:boolean,superseded:boolean):boolean{return !consumed&&!superseded&&now.getTime()>=issuedAt.getTime()&&now.getTime()-issuedAt.getTime()<5*60*1000;}
export function safeAddMoney(...values:number[]):number{let total=0;for(const value of values){if(!Number.isSafeInteger(value)||value<0)throw new Error('MONEY_INVALID');total+=value;if(!Number.isSafeInteger(total))throw new Error('MONEY_OVERFLOW');}return total;}
export function nextAmmanDeliveryDate(weekday:number,now=new Date()):string{if(!Number.isInteger(weekday)||weekday<0||weekday>6)throw new Error("WEEKDAY_INVALID");const amman=new Date(now.getTime()+3*60*60*1000);let delta=(weekday-amman.getUTCDay()+7)%7;if(delta===0)delta=7;amman.setUTCDate(amman.getUTCDate()+delta);return `${amman.getUTCFullYear()}-${String(amman.getUTCMonth()+1).padStart(2,"0")}-${String(amman.getUTCDate()).padStart(2,"0")}`;}
