"use client";
import { useState } from "react";
import { startAuthentication, startRegistration } from "@simplewebauthn/browser";

export function CtoSetup(){
  const[token,setToken]=useState("");
  const[secret,setSecret]=useState("");
  const[message,setMessage]=useState("");
  async function registerKey(){const optionsResponse=await fetch("/api/v1/setup/webauthn/options",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})});const options=await optionsResponse.json();if(!optionsResponse.ok){setMessage("Setup token invalid.");return;}const response=await startRegistration({optionsJSON:options.data});const label=prompt("Name this physical security key")??"Security key";const verify=await fetch("/api/v1/setup/webauthn/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,response,label,independentKeyAcknowledged:confirm("Is this a physically independent key stored separately?")})});setMessage(verify.ok?"Key registered. Register the separate spare too.":"Key registration failed.");}
  async function assertKey(){const optionsResponse=await fetch("/api/v1/setup/webauthn/assertion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})});const options=await optionsResponse.json();if(!optionsResponse.ok){setMessage("No registered key is ready to test.");return;}const response=await startAuthentication({optionsJSON:options.data});const verified=await fetch("/api/v1/setup/webauthn/assertion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,response})});setMessage(verified.ok?"Key assertion passed. Repeat with the physically separate key.":"Key assertion failed.");}
  async function contact(channel:"EMAIL"|"PHONE",phone?:string){const response=await fetch("/api/v1/setup/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,channel,phone})});const data=await response.json();setMessage(response.ok?(data.data.developmentCode?`Local ${channel} code: ${data.data.developmentCode}`:"Code queued securely."):"Contact verification failed.");}
  async function confirmContact(channel:"EMAIL"|"PHONE"){const code=prompt(`${channel} code`);if(!code)return;const response=await fetch("/api/v1/setup/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,channel,code})});setMessage(response.ok?`${channel} verified.`:"Code invalid.");}
  async function generateSecret(){const response=await fetch("/api/v1/setup/recovery-secret",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})});const data=await response.json();if(response.ok){setSecret(data.data.recoverySecret);setMessage("Save this passphrase now. It will not be shown again.");}else setMessage("Passphrase generation failed.");}
  async function finish(form:FormData){const response=await fetch("/api/v1/setup/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password:form.get("password"),recoverySecretConfirmation:form.get("confirmation"),savedCopyAcknowledged:form.get("saved")==="on"})});const data=await response.json();setMessage(response.ok?"CTO setup complete. Sign in with MFA.":data.error?.code??"Setup incomplete.");if(response.ok)setSecret("");}
  return <section className="panel"><label>One-use setup token<input value={token} onChange={event=>setToken(event.target.value)}/></label><div className="quick-grid"><button className="secondary" onClick={registerKey}>Register primary security key</button><button className="secondary" onClick={registerKey}>Register physically separate spare</button><button className="secondary" onClick={assertKey}>Test each registered key</button><button className="secondary" onClick={()=>contact("EMAIL")}>Send email code</button><button className="secondary" onClick={()=>confirmContact("EMAIL")}>Verify email</button><button className="secondary" onClick={()=>{const phone=prompt("Jordan phone in +962 format");if(phone)void contact("PHONE",phone);}}>Send phone code</button><button className="secondary" onClick={()=>confirmContact("PHONE")}>Verify phone</button><button className="secondary" onClick={generateSecret}>Generate one-time recovery passphrase</button></div>{secret?<output className="secret" aria-live="polite">{secret}</output>:null}<form action={finish}><label>Strong password<input name="password" type="password" minLength={12} required/></label><label>Re-enter all 12 tokens from the copy you saved<textarea name="confirmation" autoComplete="off" required/></label><label className="check"><input name="saved" type="checkbox" required/>I saved the passphrase separately and both physically independent keys passed an assertion.</label><button className="primary">Complete secure setup</button></form><p aria-live="polite">{message}</p></section>;
}
