"use client";import{useEffect,useState}from"react";import{useRouter}from"next/navigation";import{startAuthentication,startRegistration}from"@simplewebauthn/browser";import{RecoveryEntry}from"@/components/recovery-entry";type EmergencyAction="LOCKDOWN"|"COMPLETE_RECOVERY"|"CHANGE_EMAIL"|"CHANGE_PHONE"|"ADD_KEY"|"REMOVE_KEY"|"ROTATE_RECOVERY"|"REVOKE_SESSIONS";
async function api(path:string,body:unknown,method="POST"){const response=await fetch(path,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.code??"RECOVERY_FAILED");return payload.data;}
export function RecoveryConsole({emergency}:{emergency:boolean}){return emergency?<EmergencyRepair/>:<RecoveryEntry/>;}
function EmergencyRepair(){const router=useRouter();const[state,setState]=useState<{emailVerified:boolean;phoneVerified:boolean;keys:Array<{id:string;device_label:string;last_used_at:string|null}>}|null>(null);const[secret,setSecret]=useState("");const[message,setMessage]=useState("");
  async function refresh(){try{const response=await fetch("/api/v1/recovery/emergency/state");const payload=await response.json();if(response.ok)setState(payload.data);}catch{setState(null);}}
  useEffect(()=>{fetch("/api/v1/recovery/emergency/state").then(response=>response.json().then(payload=>{if(response.ok)setState(payload.data);})).catch(()=>setState(null));},[]);
  async function prove(action:EmergencyAction){const begun=await api("/api/v1/recovery/emergency/assertion",{action});const assertion=await startAuthentication({optionsJSON:begun.options});await api("/api/v1/recovery/emergency/assertion",{proofId:begun.proofId,response:assertion});return String(begun.proofId);}
  async function run(action:()=>Promise<unknown>){try{const result=await action();setMessage(JSON.stringify(result));await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Action failed");}}
  async function repairContact(form:FormData){const channel=form.get("channel")==="PHONE"?"PHONE":"EMAIL";await run(async()=>{const proofId=await prove(channel==="EMAIL"?"CHANGE_EMAIL":"CHANGE_PHONE");return api("/api/v1/recovery/emergency/contact",{proofId,channel,destination:form.get("destination")});});}
  async function confirmContact(form:FormData){await run(()=>api("/api/v1/recovery/emergency/contact",{channel:form.get("channel"),code:form.get("code")}));}
  async function addKey(){await run(async()=>{const proofId=await prove("ADD_KEY");const options=await api("/api/v1/recovery/emergency/keys",{proofId});const response=await startRegistration({optionsJSON:options});return api("/api/v1/recovery/emergency/keys",{response,label:prompt("Replacement key label")??"Replacement key"});});}
  async function rotate(){await run(async()=>{const proofId=await prove("ROTATE_RECOVERY");const result=await api("/api/v1/recovery/emergency/recovery-secret",{proofId});setSecret(result.recoverySecret);return{generated:true};});}
  async function complete(form:FormData){await run(async()=>{const proofId=await prove("COMPLETE_RECOVERY");const result=await api("/api/v1/recovery/emergency/complete",{proofId,password:form.get("password"),confirmation:form.get("confirmation"),savedCopyAcknowledged:form.get("saved")==="on",repairChecklistAcknowledged:form.get("checklist")==="on"});setSecret("");router.push("/account");return result;});}
  return <section className="panel"><h2>Restricted emergency session</h2><p>This session cannot shop, manage orders, grant roles, inspect customers, or move money.</p><p>Contacts: email {state?.emailVerified?"verified":"needs repair"} · phone {state?.phoneVerified?"verified":"needs repair"}</p><div className="list">{state?.keys.map(key=><article key={key.id}><strong>{key.device_label}</strong><small>{key.last_used_at?"assertion tested":"must be tested by a fresh assertion"}</small><button className="secondary" onClick={()=>run(async()=>{const proofId=await prove("REMOVE_KEY");return api("/api/v1/recovery/emergency/keys",{proofId,credentialId:key.id},"DELETE");})}>Remove with another key</button></article>)}</div><div className="quick-grid"><button className="secondary" onClick={()=>run(async()=>api("/api/v1/recovery/emergency/lockdown",{proofId:await prove("LOCKDOWN")}))}>Activate global lockdown</button><button className="secondary" onClick={()=>run(async()=>api("/api/v1/recovery/emergency/sessions",{proofId:await prove("REVOKE_SESSIONS")},"DELETE"))}>Revoke normal CTO sessions</button><button className="secondary" onClick={addKey}>Add replacement key</button><button className="secondary" onClick={rotate}>Generate replacement passphrase</button></div><details><summary>Repair email or phone</summary><form action={repairContact}><select name="channel"><option value="EMAIL">Email</option><option value="PHONE">Phone</option></select><input name="destination" required placeholder="New verified destination"/><button className="secondary">Send protected verification</button></form><form action={confirmContact}><select name="channel"><option value="EMAIL">Email</option><option value="PHONE">Phone</option></select><input name="code" required placeholder="Verification code"/><button className="secondary">Activate destination</button></form></details>{secret?<output className="secret">{secret}</output>:null}<form action={complete}><input name="password" type="password" minLength={12} required placeholder="New CTO password"/><textarea name="confirmation" autoComplete="off" required placeholder="Re-enter the generated 12-token passphrase"/><label className="check"><input name="saved" type="checkbox" required/>I saved the replacement passphrase securely.</label><label className="check"><input name="checklist" type="checkbox" required/>I inspected repaired contacts and tested keys; unresolved compromise checks are complete.</label><button className="primary">Finish recovery and return to normal login</button></form><button className="ghost" onClick={()=>run(()=>api("/api/v1/recovery/emergency/sessions",{exit:true},"DELETE"))}>Exit without unlocking</button><p aria-live="polite">{message}</p></section>;
}
