import{randomInt}from"node:crypto";
import{hash,verify}from"@node-rs/argon2";
import{generateAuthenticationOptions,generateRegistrationOptions,verifyAuthenticationResponse,verifyRegistrationResponse,type AuthenticationResponseJSON,type RegistrationResponseJSON}from"@simplewebauthn/server";
import{z}from"zod";
import{withDatabaseClient,withTransaction}from"@/lib/db/client";
import{appendAudit}from"@/lib/audit/service";
import type{CurrentAccount}from"@/lib/auth/session";
import{getRuntimeConfig}from"@/lib/config/env";
import{generateRecoveryPassphrase,hashToken,normalizeEmail}from"@/lib/security/crypto";
import{queueSecureDelivery}from"@/lib/notifications/secure-delivery";

export type EmergencyAction="LOCKDOWN"|"COMPLETE_RECOVERY"|"CHANGE_EMAIL"|"CHANGE_PHONE"|"ADD_KEY"|"REMOVE_KEY"|"ROTATE_RECOVERY"|"REVOKE_SESSIONS";
function requireEmergency(account:CurrentAccount){if(account.role!=="CTO"||account.sessionKind!=="EMERGENCY")throw new Error("EMERGENCY_SESSION_REQUIRED");}
export async function recordEmergencyFailure(account:CurrentAccount|null,action:string){if(!account||account.role!=="CTO"||account.sessionKind!=="EMERGENCY")return;await withTransaction(async client=>{await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"cto.recovery.action_failed",targetType:"account_session",targetId:account.sessionId,domain:"security",sensitive:true,result:"FAILED",requestContext:{action}});});}
export async function recordEmergencyContactFailure(account:CurrentAccount|null,channel:string){if(!account||account.role!=="CTO"||account.sessionKind!=="EMERGENCY"||!['EMAIL','PHONE'].includes(channel))return;await withTransaction(async client=>{await client.execute("UPDATE pending_contact_change SET failed_attempts=failed_attempts+1 WHERE session_id=$1 AND channel=$2 AND consumed_at IS NULL",[account.sessionId,channel]);await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"cto.recovery.contact_proof_failed",targetType:"account_session",targetId:account.sessionId,domain:"security",sensitive:true,result:"FAILED",requestContext:{channel}});});}

export async function beginEmergencyAction(account:CurrentAccount,action:EmergencyAction){requireEmergency(account);const config=getRuntimeConfig();return withTransaction(async client=>{const credentials=await client.execute<{id:string}>("SELECT id FROM webauthn_credential WHERE account_id=$1",[account.id]);const options=await generateAuthenticationOptions({rpID:config.WEBAUTHN_RP_ID,userVerification:"required",allowCredentials:credentials.rows.map(item=>({id:item.id}))});const challenge=await client.execute<{id:string}>("INSERT INTO webauthn_challenge(account_id,ceremony,challenge,expires_at) VALUES($1,'RECOVERY_ACTION',$2,now()+interval '5 minutes') RETURNING id",[account.id,options.challenge]);const proof=await client.execute<{id:string}>("INSERT INTO emergency_action_proof(session_id,action,challenge_id,expires_at) VALUES($1,$2,$3,now()+interval '5 minutes') RETURNING id",[account.sessionId,action,challenge.rows[0].id]);await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"cto.recovery.action_challenge_issued",targetType:"emergency_action_proof",targetId:proof.rows[0].id,domain:"security",sensitive:true,result:"PENDING",requestContext:{action,challengeId:challenge.rows[0].id,expiresInSeconds:300}});return{proofId:proof.rows[0].id,options};});}

export async function verifyEmergencyAction(account:CurrentAccount,proofId:string,response:AuthenticationResponseJSON){requireEmergency(account);const config=getRuntimeConfig();return withTransaction(async client=>{const proof=await client.execute<{challenge_id:string;challenge:string;action:string}>(`SELECT proof.challenge_id,challenge.challenge,proof.action FROM emergency_action_proof AS proof JOIN webauthn_challenge AS challenge ON challenge.id=proof.challenge_id WHERE proof.id=$1 AND proof.session_id=$2 AND proof.verified_at IS NULL AND proof.expires_at>now() AND challenge.consumed_at IS NULL FOR UPDATE OF proof,challenge`,[proofId,account.sessionId]);if(!proof.rows[0])throw new Error("ACTION_PROOF_INVALID");const stored=await client.execute<{id:string;public_key:Uint8Array;counter:number;transports:string[]}>("SELECT id,public_key,counter,transports FROM webauthn_credential WHERE account_id=$1 AND id=$2 FOR UPDATE",[account.id,response.id]);if(!stored.rows[0])throw new Error("ACTION_PROOF_INVALID");const credential=stored.rows[0];const transports=z.array(z.enum(["ble","hybrid","internal","nfc","usb"])).parse(credential.transports);const result=await verifyAuthenticationResponse({response,expectedChallenge:proof.rows[0].challenge,expectedOrigin:config.ADMIN_ORIGIN,expectedRPID:config.WEBAUTHN_RP_ID,credential:{id:credential.id,publicKey:Uint8Array.from(credential.public_key),counter:credential.counter,transports},requireUserVerification:true});if(!result.verified)throw new Error("ACTION_PROOF_INVALID");await client.execute("UPDATE emergency_action_proof SET verified_at=now(),credential_id=$2 WHERE id=$1",[proofId,credential.id]);await client.execute("UPDATE webauthn_challenge SET consumed_at=now() WHERE id=$1",[proof.rows[0].challenge_id]);await client.execute("UPDATE webauthn_credential SET counter=$2,last_used_at=now() WHERE id=$1",[credential.id,result.authenticationInfo.newCounter]);await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"cto.recovery.action_asserted",targetType:"emergency_action_proof",targetId:proofId,domain:"security",sensitive:true,requestContext:{action:proof.rows[0].action,credentialId:credential.id}});return{verified:true};});}

async function consumeActionProof(client:import("@/lib/db/client").DatabaseClient,account:CurrentAccount,proofId:string,action:EmergencyAction){const proof=await client.execute<{credential_id:string}>("UPDATE emergency_action_proof SET consumed_at=now() WHERE id=$1 AND session_id=$2 AND action=$3 AND verified_at>now()-interval '5 minutes' AND consumed_at IS NULL RETURNING credential_id",[proofId,account.sessionId,action]);if(!proof.rows[0]?.credential_id)throw new Error("FRESH_ASSERTION_REQUIRED");return proof.rows[0].credential_id;}

export async function inspectEmergencyState(account:CurrentAccount){requireEmergency(account);return withDatabaseClient(async client=>{const[state,keys]=await Promise.all([client.execute<{email_verified_at:Date|null;phone_verified_at:Date|null}>("SELECT email_verified_at,phone_verified_at FROM account WHERE id=$1",[account.id]),client.execute<{id:string;device_label:string;created_at:Date;last_used_at:Date|null}>("SELECT id,device_label,created_at,last_used_at FROM webauthn_credential WHERE account_id=$1 ORDER BY created_at",[account.id])]);return{emailVerified:Boolean(state.rows[0]?.email_verified_at),phoneVerified:Boolean(state.rows[0]?.phone_verified_at),keys:keys.rows};});}

export async function activateLockdown(account:CurrentAccount,proofId:string){requireEmergency(account);return withTransaction(async client=>{await consumeActionProof(client,account,proofId,"LOCKDOWN");await client.execute("UPDATE platform_state SET normal_operations_locked=true,lockdown_reason_code='CTO_RECOVERY',updated_at=now() WHERE singleton=true");await client.execute("UPDATE account_session SET revoked_at=now() WHERE kind='NORMAL' AND revoked_at IS NULL");await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"security.global_lockdown.activated",targetType:"platform",targetId:"singleton",domain:"security",sensitive:true});return{locked:true};});}

export async function issueEmergencyContactCode(account:CurrentAccount,proofId:string,channel:"EMAIL"|"PHONE",destination:string){requireEmergency(account);const normalized=channel==="EMAIL"?normalizeEmail(destination):destination;if(channel==="EMAIL"&&!z.string().email().safeParse(normalized).success)throw new Error("EMAIL_INVALID");if(channel==="PHONE"&&!/^\+962[0-9]{8,9}$/.test(normalized))throw new Error("PHONE_INVALID");const code=String(randomInt(100000,1000000));await withTransaction(async client=>{await consumeActionProof(client,account,proofId,channel==="EMAIL"?"CHANGE_EMAIL":"CHANGE_PHONE");await client.execute("INSERT INTO pending_contact_change(session_id,channel,destination,verifier_hash,expires_at) VALUES($1,$2,$3,$4,now()+interval '5 minutes') ON CONFLICT(session_id,channel) DO UPDATE SET destination=EXCLUDED.destination,verifier_hash=EXCLUDED.verifier_hash,failed_attempts=0,expires_at=EXCLUDED.expires_at,consumed_at=NULL",[account.sessionId,channel,normalized,hashToken(code)]);await queueSecureDelivery(client,{eventType:"security.cto.emergency_contact.v1",aggregateType:"account_session",aggregateId:account.sessionId,accountId:account.id,channel,destination:normalized,token:code,expiresAt:new Date(Date.now()+5*60*1000)});const preset=getRuntimeConfig().SECURITY_ALERT_EMAIL;if(preset&&preset!==normalized)await queueSecureDelivery(client,{eventType:"security.cto.recovery_warning.v1",aggregateType:"account_session",aggregateId:account.sessionId,accountId:account.id,channel:"EMAIL",destination:preset,token:"",expiresAt:new Date(Date.now()+5*60*1000)});await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"recovery.contact_change.requested",targetType:"account",targetId:account.id,domain:"security",sensitive:true,after:{field:channel}});});return{sent:true,developmentCode:["local","test"].includes(getRuntimeConfig().APP_ENV)?code:undefined};}

export async function confirmEmergencyContactCode(account:CurrentAccount,channel:"EMAIL"|"PHONE",code:string){requireEmergency(account);return withTransaction(async client=>{const change=await client.execute<{id:string;destination:string;failed_attempts:number}>("SELECT id,destination,failed_attempts FROM pending_contact_change WHERE session_id=$1 AND channel=$2 AND verifier_hash=$3 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE",[account.sessionId,channel,hashToken(code)]);const row=change.rows[0];if(!row){await client.execute("UPDATE pending_contact_change SET failed_attempts=failed_attempts+1 WHERE session_id=$1 AND channel=$2",[account.sessionId,channel]);throw new Error("CONTACT_CODE_INVALID");}if(row.failed_attempts>=5)throw new Error("CONTACT_CODE_INVALID");await client.execute("UPDATE pending_contact_change SET consumed_at=now() WHERE id=$1",[row.id]);await client.execute(channel==="EMAIL"?"UPDATE account SET email_normalized=$2,pending_email_normalized=NULL,email_verified_at=now(),updated_at=now() WHERE id=$1":"UPDATE account SET phone_e164=$2,phone_verified_at=now(),updated_at=now() WHERE id=$1",[account.id,row.destination]);await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"recovery.contact.changed",targetType:"account",targetId:account.id,domain:"security",sensitive:true,after:{field:channel}});return{verified:true};});}

export async function beginEmergencyKeyRegistration(account:CurrentAccount,proofId:string){requireEmergency(account);const config=getRuntimeConfig();return withTransaction(async client=>{await consumeActionProof(client,account,proofId,"ADD_KEY");const existing=await client.execute<{id:string}>("SELECT id FROM webauthn_credential WHERE account_id=$1",[account.id]);const options=await generateRegistrationOptions({rpName:config.WEBAUTHN_RP_NAME,rpID:config.WEBAUTHN_RP_ID,userID:new TextEncoder().encode(account.id),userName:account.email,userDisplayName:account.displayName,attestationType:"none",excludeCredentials:existing.rows.map(item=>({id:item.id})),authenticatorSelection:{residentKey:"preferred",userVerification:"required"}});await client.execute("INSERT INTO webauthn_challenge(account_id,ceremony,challenge,expires_at) VALUES($1,'REGISTRATION',$2,now()+interval '5 minutes')",[account.id,options.challenge]);return options;});}

export async function finishEmergencyKeyRegistration(account:CurrentAccount,response:RegistrationResponseJSON,label:string){requireEmergency(account);const config=getRuntimeConfig();return withTransaction(async client=>{const challenge=await client.execute<{id:string;challenge:string}>("SELECT id,challenge FROM webauthn_challenge WHERE account_id=$1 AND ceremony='REGISTRATION' AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1 FOR UPDATE",[account.id]);if(!challenge.rows[0])throw new Error("CHALLENGE_INVALID");const verification=await verifyRegistrationResponse({response,expectedChallenge:challenge.rows[0].challenge,expectedOrigin:config.ADMIN_ORIGIN,expectedRPID:config.WEBAUTHN_RP_ID,requireUserVerification:true});if(!verification.verified||!verification.registrationInfo)throw new Error("WEBAUTHN_INVALID");const credential=verification.registrationInfo.credential;await client.execute("INSERT INTO webauthn_credential(id,account_id,public_key,counter,transports,device_label,independent_key) VALUES($1,$2,$3,$4,$5,$6,true)",[credential.id,account.id,Buffer.from(credential.publicKey),credential.counter,credential.transports??[],label.slice(0,100)]);await client.execute("UPDATE webauthn_challenge SET consumed_at=now() WHERE id=$1",[challenge.rows[0].id]);await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"recovery.security_key.added",targetType:"webauthn_credential",targetId:credential.id,domain:"security",sensitive:true});return{registered:true,requiresTestAssertion:true};});}

export async function removeEmergencyKey(account:CurrentAccount,proofId:string,credentialId:string){requireEmergency(account);return withTransaction(async client=>{const assertingCredential=await consumeActionProof(client,account,proofId,"REMOVE_KEY");if(assertingCredential===credentialId)throw new Error("ASSERTING_KEY_CANNOT_REMOVE_ITSELF");const count=await client.execute<{count:number}>("SELECT count(*)::int AS count FROM webauthn_credential WHERE account_id=$1",[account.id]);if(count.rows[0].count<2)throw new Error("LAST_KEY_PROTECTED");const removed=await client.execute("DELETE FROM webauthn_credential WHERE account_id=$1 AND id=$2 RETURNING id",[account.id,credentialId]);if(!removed.rowCount)throw new Error("KEY_NOT_FOUND");await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"recovery.security_key.removed",targetType:"webauthn_credential",targetId:credentialId,domain:"security",sensitive:true});return{removed:true};});}

export async function generateEmergencyRecoverySecret(account:CurrentAccount,proofId:string){requireEmergency(account);const secret=generateRecoveryPassphrase();const verifierHash=await hash(secret,{memoryCost:19456,timeCost:2,parallelism:1});await withTransaction(async client=>{await consumeActionProof(client,account,proofId,"ROTATE_RECOVERY");await client.execute("INSERT INTO pending_recovery_secret(account_id,verifier_hash,expires_at) VALUES($1,$2,now()+interval '30 minutes') ON CONFLICT(account_id) DO UPDATE SET verifier_hash=EXCLUDED.verifier_hash,failed_attempts=0,expires_at=EXCLUDED.expires_at,created_at=now()",[account.id,verifierHash]);});return{recoverySecret:secret};}

export async function revokeEmergencySessions(account:CurrentAccount,proofId:string){requireEmergency(account);return withTransaction(async client=>{await consumeActionProof(client,account,proofId,"REVOKE_SESSIONS");const result=await client.execute("UPDATE account_session SET revoked_at=now() WHERE account_id=$1 AND kind='NORMAL' AND revoked_at IS NULL",[account.id]);await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"recovery.normal_sessions.revoked",targetType:"account",targetId:account.id,domain:"security",sensitive:true,after:{count:result.rowCount??0}});return{revoked:result.rowCount??0};});}

export async function finishEmergencyRecovery(account:CurrentAccount,input:{password:string;recoverySecret?:string;confirmation:string;savedCopyAcknowledged:boolean;repairChecklistAcknowledged:boolean;proofId:string}){requireEmergency(account);if(input.password.length<12||input.confirmation.trim().split(/\s+/).length!==12||!input.savedCopyAcknowledged||!input.repairChecklistAcknowledged)throw new Error("RECOVERY_COMPLETION_INCOMPLETE");const pending=await withDatabaseClient(async client=>(await client.execute<{verifier_hash:string;failed_attempts:number}>("SELECT verifier_hash,failed_attempts FROM pending_recovery_secret WHERE account_id=$1 AND expires_at>now()",[account.id])).rows[0]);if(!pending||pending.failed_attempts>=5||!await verify(pending.verifier_hash,input.confirmation)){await withDatabaseClient(client=>client.execute("UPDATE pending_recovery_secret SET failed_attempts=failed_attempts+1 WHERE account_id=$1",[account.id]).then(()=>undefined));throw new Error("SAVED_PASSPHRASE_CHECK_FAILED");}const passwordHash=await hash(input.password,{memoryCost:19456,timeCost:2,parallelism:1});return withTransaction(async client=>{await consumeActionProof(client,account,input.proofId,"COMPLETE_RECOVERY");const keys=await client.execute("SELECT id FROM webauthn_credential WHERE account_id=$1 AND last_used_at IS NOT NULL",[account.id]);const contacts=await client.execute<{email_verified_at:Date|null;phone_verified_at:Date|null}>("SELECT email_verified_at,phone_verified_at FROM account WHERE id=$1 FOR UPDATE",[account.id]);if(!keys.rowCount||!contacts.rows[0]?.email_verified_at||!contacts.rows[0]?.phone_verified_at)throw new Error("RECOVERY_COMPLETION_INCOMPLETE");await client.execute("UPDATE account SET password_hash=$2,password_changed_at=now(),updated_at=now() WHERE id=$1",[account.id,passwordHash]);await client.execute("UPDATE recovery_secret SET verifier_hash=$2,generation=generation+1,rotated_at=now(),saved_check_at=now(),consumed_at=NULL WHERE account_id=$1",[account.id,pending.verifier_hash]);await client.execute("DELETE FROM pending_recovery_secret WHERE account_id=$1",[account.id]);await client.execute("UPDATE platform_state SET normal_operations_locked=false,lockdown_reason_code=NULL,updated_at=now() WHERE singleton=true");await client.execute("UPDATE account_session SET revoked_at=now() WHERE id=$1",[account.sessionId]);await appendAudit(client,{actorId:account.id,actorRole:"CTO",action:"cto.recovery.completed",targetType:"account",targetId:account.id,domain:"security",sensitive:true});return{completed:true,normalLoginRequired:true};});}

export async function exitEmergencySession(account:CurrentAccount){requireEmergency(account);await withDatabaseClient(client=>client.execute("UPDATE account_session SET revoked_at=now() WHERE id=$1",[account.sessionId]).then(()=>undefined));return{exited:true};}
