import { z } from "zod";
import { withDatabaseClient, withTransaction } from "@/lib/db/client";
import { hashToken } from "@/lib/security/crypto";

const lineInput=z.object({variantId:z.string().uuid(),quantity:z.number().int().min(1).max(99),selected:z.boolean().default(true)});
export type CartOwner={accountId:string;anonymousToken?:never}|{accountId?:never;anonymousToken:string};
export type CartLine={id:string;variant_id:string;quantity:number;selected:boolean;sku:string;option_values:Record<string,string>;slug:string;name_en:string;name_ar:string;unit_price_fils:string;available:number|null};
function ownerValues(owner:CartOwner){return{accountId:owner.accountId??null,anonymousHash:owner.anonymousToken?hashToken(owner.anonymousToken):null};}

export async function getCart(owner:CartOwner){const values=ownerValues(owner);return withDatabaseClient(async client=>(await client.execute<CartLine>(`SELECT line.id,line.variant_id,line.quantity,line.selected,variant.sku,variant.option_values,product.slug,product.name_en,product.name_ar,COALESCE(variant.price_override_fils,product.base_price_fils) AS unit_price_fils,CASE WHEN variant.inventory_tracking THEN balance.on_hand-balance.reserved ELSE NULL END AS available FROM cart JOIN cart_line AS line ON line.cart_id=cart.id JOIN product_variant AS variant ON variant.id=line.variant_id JOIN product ON product.id=variant.product_id LEFT JOIN inventory_balance AS balance ON balance.variant_id=variant.id WHERE (cart.account_id=$1::uuid OR cart.anonymous_token_hash=$2) ORDER BY line.updated_at`,[values.accountId,values.anonymousHash])).rows);}

export async function upsertCartLine(owner:CartOwner,raw:unknown){const input=lineInput.parse(raw);const values=ownerValues(owner);await withTransaction(async client=>{const sellable=await client.execute(`SELECT 1 FROM product_variant JOIN product ON product.id=product_variant.product_id WHERE product_variant.id=$1 AND product_variant.enabled AND product_variant.purchasable AND product.status='ACTIVE'`,[input.variantId]);if(!sellable.rowCount)throw new Error("VARIANT_UNAVAILABLE");const cart=values.accountId?await client.execute<{id:string}>("INSERT INTO cart(account_id) VALUES($1) ON CONFLICT(account_id) DO UPDATE SET updated_at=now() RETURNING id",[values.accountId]):await client.execute<{id:string}>("INSERT INTO cart(anonymous_token_hash) VALUES($1) ON CONFLICT(anonymous_token_hash) DO UPDATE SET updated_at=now() RETURNING id",[values.anonymousHash]);await client.execute(`INSERT INTO cart_line(cart_id,variant_id,quantity,selected) VALUES($1,$2,$3,$4) ON CONFLICT(cart_id,variant_id) DO UPDATE SET quantity=EXCLUDED.quantity,selected=EXCLUDED.selected,updated_at=now()`,[cart.rows[0].id,input.variantId,input.quantity,input.selected]);});}

export async function removeCartLine(owner:CartOwner,lineId:string){const values=ownerValues(owner);await withDatabaseClient(client=>client.execute("DELETE FROM cart_line USING cart WHERE cart_line.cart_id=cart.id AND (cart.account_id=$1::uuid OR cart.anonymous_token_hash=$2) AND cart_line.id=$3",[values.accountId,values.anonymousHash,lineId]).then(()=>undefined));}

export async function mergeAnonymousCart(accountId:string,anonymousToken:string){const anonymousHash=hashToken(anonymousToken);return withTransaction(async client=>{const source=await client.execute<{id:string}>("SELECT id FROM cart WHERE anonymous_token_hash=$1 FOR UPDATE",[anonymousHash]);if(!source.rows[0])return{merged:0};const target=await client.execute<{id:string}>("INSERT INTO cart(account_id) VALUES($1) ON CONFLICT(account_id) DO UPDATE SET updated_at=now() RETURNING id",[accountId]);const merged=await client.execute(`INSERT INTO cart_line(cart_id,variant_id,quantity,selected) SELECT $1,variant_id,quantity,false FROM cart_line WHERE cart_id=$2 ON CONFLICT(cart_id,variant_id) DO UPDATE SET quantity=LEAST(99,cart_line.quantity+EXCLUDED.quantity),selected=false,updated_at=now() RETURNING id`,[target.rows[0].id,source.rows[0].id]);await client.execute("DELETE FROM cart WHERE id=$1",[source.rows[0].id]);return{merged:merged.rowCount??0,selectionConfirmationRequired:(merged.rowCount??0)>0};});}
