import{z}from"zod";
import{withDatabaseClient,withTransaction}from"@/lib/db/client";
import{appendAudit}from"@/lib/audit/service";
import{appendDomainEvent}from"@/lib/events/outbox";
import{deleteObjectKey}from"@/lib/media/service";
import{queueSecureDelivery}from"@/lib/notifications/secure-delivery";

const ticketInput=z.object({category:z.enum(["ORDER","DAMAGE","DELIVERY","PAYMENT","ACCOUNT","PRODUCT","REFERRAL","VERIFICATION","PROMOTION","OTHER"]),subject:z.string().min(3).max(200),message:z.string().min(1).max(10000),orderId:z.string().max(100).optional(),mediaIds:z.array(z.string().uuid()).max(5).default([])});
export async function createTicket(accountId:string,raw:unknown){const input=ticketInput.parse(raw);return withTransaction(async client=>{
  let orderId:string|null=null;
  if(input.orderId){const owned=await client.execute<{id:string}>("SELECT id FROM shop_order WHERE (id::text=$1 OR public_id=$1) AND account_id=$2",[input.orderId,accountId]);if(!owned.rows[0])throw new Error("ORDER_NOT_FOUND");orderId=owned.rows[0].id;}
  const ticket=await client.execute<{id:string;public_id:string}>("INSERT INTO support_ticket(account_id,order_id,category,subject) VALUES($1,$2,$3,$4) RETURNING id,public_id",[accountId,orderId,input.category,input.subject]);
  await client.execute("INSERT INTO ticket_message(ticket_id,author_id,body) VALUES($1,$2,$3)",[ticket.rows[0].id,accountId,input.message]);
  if(input.mediaIds.length){const media=await client.execute("UPDATE media_object SET owner_type='TICKET',owner_id=$2 WHERE id=ANY($1::uuid[]) AND owner_type='ACCOUNT_UPLOAD' AND owner_id=$3 AND access_class='PRIVATE' AND scan_status='CLEAN' AND deleted_at IS NULL RETURNING id",[input.mediaIds,ticket.rows[0].id,accountId]);if(media.rowCount!==input.mediaIds.length)throw new Error("TICKET_MEDIA_INVALID");}
  await appendDomainEvent(client,{eventType:"support.ticket.created.v1",aggregateType:"ticket",aggregateId:ticket.rows[0].id,payload:{ticketId:ticket.rows[0].id}});
  return ticket.rows[0];
});}

export async function listOwnTickets(accountId:string){return withDatabaseClient(async client=>(await client.execute("SELECT public_id,category,priority,status,subject,created_at,updated_at FROM support_ticket WHERE account_id=$1 ORDER BY updated_at DESC",[accountId])).rows);}
export async function listSupportQueue(){return withDatabaseClient(async client=>(await client.execute("SELECT ticket.public_id,ticket.category,ticket.priority,ticket.status,ticket.subject,ticket.created_at,ticket.updated_at,account.public_id AS customer_public_id,account.display_name AS customer_name FROM support_ticket AS ticket JOIN account ON account.id=ticket.account_id ORDER BY CASE ticket.priority WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,ticket.updated_at DESC LIMIT 200")).rows);}
export async function ticketConversation(publicId:string,accountId:string,isStaff=false){return withTransaction(async client=>{const ticket=await client.execute<{id:string;account_id:string;public_id:string;status:string;subject:string}>("SELECT id,account_id,public_id,status,subject FROM support_ticket WHERE public_id=$1",[publicId]);const row=ticket.rows[0];if(!row||(!isStaff&&row.account_id!==accountId))throw new Error("TICKET_NOT_FOUND");const messages=await client.execute("SELECT message.id,message.body,message.private_note,message.edited_at,message.created_at,account.public_id AS author_public_id,account.display_name AS author_name,(message.author_id=$2 AND $3<>'CLOSED') AS editable,(SELECT count(*)::int FROM ticket_message_revision WHERE message_id=message.id) AS revision_count FROM ticket_message AS message JOIN account ON account.id=message.author_id WHERE message.ticket_id=$1 AND ($4 OR NOT message.private_note) ORDER BY message.created_at",[row.id,accountId,row.status,isStaff]);await client.execute("INSERT INTO ticket_read_state(ticket_id,account_id,last_read_at) VALUES($1,$2,now()) ON CONFLICT(ticket_id,account_id) DO UPDATE SET last_read_at=EXCLUDED.last_read_at",[row.id,accountId]);return{...row,messages:messages.rows};});}
export async function editTicketMessage(publicId:string,messageId:string,actorId:string,body:string,isStaff=false){if(body.trim().length<1||body.length>10000)throw new Error("MESSAGE_INVALID");return withTransaction(async client=>{const message=await client.execute<{id:string;body:string;author_id:string;account_id:string;status:string}>(`SELECT message.id,message.body,message.author_id,ticket.account_id,ticket.status FROM ticket_message AS message JOIN support_ticket AS ticket ON ticket.id=message.ticket_id WHERE ticket.public_id=$1 AND message.id=$2 FOR UPDATE OF message,ticket`,[publicId,messageId]);const row=message.rows[0];if(!row||row.author_id!==actorId||(!isStaff&&row.account_id!==actorId)||row.status==="CLOSED")throw new Error("MESSAGE_NOT_EDITABLE");if(row.body===body.trim())return{edited:false};await client.execute("INSERT INTO ticket_message_revision(message_id,editor_id,previous_body) VALUES($1,$2,$3)",[row.id,actorId,row.body]);await client.execute("UPDATE ticket_message SET body=$2,edited_at=now() WHERE id=$1",[row.id,body.trim()]);await appendAudit(client,{actorId,action:"ticket.message.edited",targetType:"ticket_message",targetId:row.id,domain:"support"});return{edited:true};});}
export async function replyTicket(publicId:string,actorId:string,body:string,isStaff=false,privateNote=false){if(body.trim().length<1||body.length>10000)throw new Error("MESSAGE_INVALID");if(privateNote&&!isStaff)throw new Error("PRIVATE_NOTE_DENIED");return withTransaction(async client=>{const ticket=await client.execute<{id:string;account_id:string;status:string}>("SELECT id,account_id,status FROM support_ticket WHERE public_id=$1 FOR UPDATE",[publicId]);const row=ticket.rows[0];if(!row||(!isStaff&&row.account_id!==actorId)||row.status==="CLOSED")throw new Error("TICKET_NOT_REPLYABLE");await client.execute("INSERT INTO ticket_message(ticket_id,author_id,body,private_note) VALUES($1,$2,$3,$4)",[row.id,actorId,body.trim(),privateNote]);await client.execute("UPDATE support_ticket SET status=$2,updated_at=now() WHERE id=$1",[row.id,isStaff?"AWAITING_CUSTOMER":"AWAITING_STAFF"]);if(!privateNote)await appendDomainEvent(client,{eventType:"support.ticket.replied.v1",aggregateType:"ticket",aggregateId:row.id,payload:{ticketId:row.id}});return{replied:true};});}
export async function closeTicket(publicId:string,actorId:string,isStaff=false){return withTransaction(async client=>{const ticket=await client.execute<{id:string;account_id:string}>("SELECT id,account_id FROM support_ticket WHERE public_id=$1 FOR UPDATE",[publicId]);const row=ticket.rows[0];if(!row||(!isStaff&&row.account_id!==actorId))throw new Error("TICKET_NOT_FOUND");await client.execute("UPDATE support_ticket SET status='CLOSED',closed_at=now(),attachment_purge_at=now()+interval '14 days',updated_at=now() WHERE id=$1",[row.id]);await appendAudit(client,{actorId,action:"ticket.closed",targetType:"ticket",targetId:row.id,domain:"support"});return{closed:true};});}
export async function setTicketStatus(publicId:string,actorId:string,status:"OPEN"|"AWAITING_CUSTOMER"|"AWAITING_STAFF"|"IN_REVIEW"|"RESOLVED"|"CLOSED"){if(status==="CLOSED")return closeTicket(publicId,actorId,true);return withTransaction(async client=>{const result=await client.execute<{id:string}>("UPDATE support_ticket SET status=$2,closed_at=NULL,attachment_purge_at=NULL,updated_at=now() WHERE public_id=$1 RETURNING id",[publicId,status]);if(!result.rows[0])throw new Error("TICKET_NOT_FOUND");await appendAudit(client,{actorId,action:"ticket.status.changed",targetType:"ticket",targetId:result.rows[0].id,domain:"support",after:{status}});return{status};});}
export async function updateTicketOperations(publicId:string,actorId:string,input:{category?:string;priority?:"LOW"|"NORMAL"|"HIGH"|"URGENT";assignedTo?:string|null}){return withTransaction(async client=>{if(input.assignedTo){const valid=await client.execute("SELECT 1 FROM staff_account JOIN role_permission ON role_permission.role_id=staff_account.role_id WHERE staff_account.account_id=$1 AND staff_account.status='ACTIVE' AND role_permission.permission_id='support.manage'",[input.assignedTo]);if(!valid.rowCount)throw new Error("ASSIGNEE_INVALID");}const before=await client.execute("SELECT category,priority,assigned_to FROM support_ticket WHERE public_id=$1 FOR UPDATE",[publicId]);if(!before.rows[0])throw new Error("TICKET_NOT_FOUND");await client.execute("UPDATE support_ticket SET category=COALESCE($2,category),priority=COALESCE($3,priority),assigned_to=CASE WHEN $4 THEN $5 ELSE assigned_to END,updated_at=now() WHERE public_id=$1",[publicId,input.category??null,input.priority??null,Object.hasOwn(input,"assignedTo"),input.assignedTo??null]);await appendAudit(client,{actorId,action:"ticket.operations.updated",targetType:"ticket",targetId:publicId,domain:"support",before:before.rows[0],after:input});return{updated:true};});}
export async function reopenTicket(publicId:string,accountId:string){return withTransaction(async client=>{const result=await client.execute("UPDATE support_ticket SET status='OPEN',closed_at=NULL,attachment_purge_at=NULL,updated_at=now() WHERE public_id=$1 AND account_id=$2 AND status IN ('RESOLVED','CLOSED') RETURNING id",[publicId,accountId]);if(!result.rowCount)throw new Error("TICKET_NOT_REOPENABLE");return{reopened:true};});}

const claimInput=z.object({orderLineId:z.string().uuid(),quantity:z.number().int().min(1),description:z.string().min(10).max(5000),mediaIds:z.array(z.string().uuid()).min(1).max(5)});
export async function createDamageClaim(accountId:string,raw:unknown){const input=claimInput.parse(raw);return withTransaction(async client=>{
  const line=await client.execute<{order_id:string;quantity:number;refunded_quantity:number;delivered_at:Date|null}>(`SELECT orders.id AS order_id,line.quantity,line.refunded_quantity,orders.delivered_at FROM order_line AS line JOIN shop_order AS orders ON orders.id=line.order_id WHERE line.id=$1 AND orders.account_id=$2 FOR UPDATE OF line`,[input.orderLineId,accountId]);
  const row=line.rows[0];if(!row?.delivered_at)throw new Error("CLAIM_NOT_ELIGIBLE");if(Date.now()-new Date(row.delivered_at).getTime()>7*86400000)throw new Error("CLAIM_WINDOW_EXPIRED");
  const claimed=await client.execute<{total:string}>("SELECT COALESCE(SUM(quantity),0) AS total FROM damage_claim WHERE order_line_id=$1 AND status<>'REJECTED'",[input.orderLineId]);if(Number(claimed.rows[0].total)+input.quantity>row.quantity-row.refunded_quantity)throw new Error("CLAIM_QUANTITY_EXCEEDED");
  const media=await client.execute("SELECT id FROM media_object WHERE id=ANY($1::uuid[]) AND owner_type='ACCOUNT_UPLOAD' AND owner_id=$2 AND access_class='PRIVATE' AND scan_status='CLEAN' AND deleted_at IS NULL FOR UPDATE",[input.mediaIds,accountId]);if(media.rowCount!==input.mediaIds.length)throw new Error("CLAIM_MEDIA_REQUIRED");
  const ticket=await client.execute<{id:string;public_id:string}>("INSERT INTO support_ticket(account_id,order_id,category,priority,subject) VALUES($1,$2,'DAMAGE','HIGH','Damage claim') RETURNING id,public_id",[accountId,row.order_id]);
  const claim=await client.execute<{id:string}>("INSERT INTO damage_claim(ticket_id,order_line_id,quantity,description) VALUES($1,$2,$3,$4) RETURNING id",[ticket.rows[0].id,input.orderLineId,input.quantity,input.description]);
  await client.execute("UPDATE media_object SET owner_type='TICKET',owner_id=$2 WHERE id=ANY($1::uuid[])",[input.mediaIds,ticket.rows[0].id]);
  await appendDomainEvent(client,{eventType:"support.damage.requested.v1",aggregateType:"claim",aggregateId:claim.rows[0].id,payload:{claimId:claim.rows[0].id}});
  return{ticketId:ticket.rows[0].public_id,claimId:claim.rows[0].id};
});}

export async function decideDamageClaim(claimId:string,actorId:string,input:{decision:"REPLACE"|"REFUND"|"REJECT";customerReason:string;privateNotes?:string}){return withTransaction(async client=>{
  const claim=await client.execute<{id:string;status:string;quantity:number;order_line_id:string}>("SELECT id,status,quantity,order_line_id FROM damage_claim WHERE id=$1 FOR UPDATE",[claimId]);const row=claim.rows[0];if(!row||!["REQUESTED","UNDER_REVIEW"].includes(row.status))throw new Error("CLAIM_NOT_DECIDABLE");
  if(input.decision==="REJECT"){await client.execute("UPDATE damage_claim SET status='REJECTED',customer_safe_reason=$2,private_notes=$3,decided_by=$4,updated_at=now() WHERE id=$1",[row.id,input.customerReason,input.privateNotes??null,actorId]);return{status:"REJECTED"};}
  const line=await client.execute<{order_id:string;variant_id:string;unit_net_fils:string;refunded_quantity:number;quantity:number;payment_method:string;collected_fils:string}>("SELECT line.order_id,line.variant_id,line.unit_net_fils,line.refunded_quantity,line.quantity,orders.payment_method,orders.collected_fils FROM order_line AS line JOIN shop_order AS orders ON orders.id=line.order_id WHERE line.id=$1 FOR UPDATE OF line,orders",[row.order_line_id]);if(!line.rows[0]||line.rows[0].refunded_quantity+row.quantity>line.rows[0].quantity)throw new Error("CLAIM_QUANTITY_EXCEEDED");
  const balance=await client.execute<{available:number}>("SELECT on_hand-reserved AS available FROM inventory_balance WHERE variant_id=$1 FOR UPDATE",[line.rows[0].variant_id]);
  if(input.decision==="REPLACE"&&Number(balance.rows[0]?.available)>=row.quantity){
    const replacement=await client.execute<{id:string;public_id:string}>(`INSERT INTO shop_order(account_id,status,payment_status,fulfillment_status,payment_method,merchandise_fils,delivery_fils,external_due_fils,quote_snapshot,recipient_snapshot,delivery_snapshot,terms_document_id,placed_at) SELECT account_id,'CONFIRMED','PAID','UNFULFILLED','ZERO_VALUE',0,0,0,jsonb_build_object('replacementFor',$1),recipient_snapshot,delivery_snapshot,terms_document_id,now() FROM shop_order WHERE id=$1 RETURNING id,public_id`,[line.rows[0].order_id]);
    const replacementLine=await client.execute<{id:string}>(`INSERT INTO order_line(order_id,variant_id,product_id,sku,name_snapshot,options_snapshot,image_snapshot,quantity,unit_base_fils,unit_net_fils) SELECT $2,variant_id,product_id,sku,name_snapshot,options_snapshot,image_snapshot,$3,unit_base_fils,0 FROM order_line WHERE id=$1 RETURNING id`,[row.order_line_id,replacement.rows[0].id,row.quantity]);
    const reserved=await client.execute("UPDATE inventory_balance SET reserved=reserved+$2,updated_at=now() WHERE variant_id=$1 AND on_hand-reserved>=$2",[line.rows[0].variant_id,row.quantity]);if(!reserved.rowCount)throw new Error("INSUFFICIENT_STOCK");
    await client.execute("INSERT INTO stock_allocation(order_line_id,variant_id,quantity,status) VALUES($1,$2,$3,'COMMITTED')",[replacementLine.rows[0].id,line.rows[0].variant_id,row.quantity]);
    await client.execute(`INSERT INTO stock_movement(variant_id,kind,reserved_delta,on_hand_after,reserved_after,source_type,source_id,actor_id,reason) SELECT variant_id,'RESERVE',$2,on_hand,reserved,'REPLACEMENT',$3,$4,'Approved damage replacement' FROM inventory_balance WHERE variant_id=$1`,[line.rows[0].variant_id,row.quantity,replacement.rows[0].id,actorId]);
    await client.execute("INSERT INTO shipment(order_id,internal_reference,expected_cash_fils) VALUES($1,'SHP-'||upper(substr($2,5)),0)",[replacement.rows[0].id,replacement.rows[0].public_id]);
    await client.execute("UPDATE damage_claim SET status='REPLACEMENT_CREATED',replacement_order_id=$2,customer_safe_reason=$3,private_notes=$4,decided_by=$5,updated_at=now() WHERE id=$1",[row.id,replacement.rows[0].id,input.customerReason,input.privateNotes??null,actorId]);
    await appendAudit(client,{actorId,action:"claim.replacement_authorized",targetType:"damage_claim",targetId:row.id,domain:"support",reason:input.customerReason});return{status:"REPLACEMENT_CREATED",replacementOrderId:replacement.rows[0].public_id};
  }
  if(input.decision==="REPLACE")throw new Error("REPLACEMENT_STOCK_UNAVAILABLE");
  const amount=Number(line.rows[0].unit_net_fils)*row.quantity;if(Number(line.rows[0].collected_fils)<amount)throw new Error("REFUND_EXCEEDS_COLLECTED");const refund=await client.execute<{id:string}>("INSERT INTO refund(order_id,payment_id,claim_id,amount_fils,reason,status,approved_by) VALUES($1,(SELECT id FROM payment WHERE order_id=$1 AND status='CONFIRMED' ORDER BY created_at LIMIT 1),$2,$3,'DAMAGED_ITEM','REQUIRED',$4) RETURNING id",[line.rows[0].order_id,row.id,amount,actorId]);
  await client.execute("UPDATE order_line SET refunded_quantity=refunded_quantity+$2 WHERE id=$1",[row.order_line_id,row.quantity]);
  await client.execute("UPDATE damage_claim SET status='REFUND_REQUESTED',customer_safe_reason=$2,private_notes=$3,decided_by=$4,updated_at=now() WHERE id=$1",[row.id,input.customerReason,input.privateNotes??null,actorId]);
  await appendAudit(client,{actorId,action:"claim.refund_authorized",targetType:"damage_claim",targetId:row.id,domain:"support",reason:input.customerReason});return{status:"REFUND_REQUESTED",refundId:refund.rows[0].id};
});}

export async function requestDeletion(accountId:string){return withTransaction(async client=>{
  const account=await client.execute<{status:string;role_id:string|null}>(`SELECT account.status,staff.role_id FROM account LEFT JOIN staff_account AS staff ON staff.account_id=account.id WHERE account.id=$1 FOR UPDATE OF account`,[accountId]);
  if(!account.rows[0]||account.rows[0].role_id||["DELETED","DISABLED","DELETION_PENDING"].includes(account.rows[0].status))throw new Error("ACCOUNT_INELIGIBLE");
  const due=new Date(Date.now()+14*86400000);
  await client.execute("UPDATE account SET status='DELETION_PENDING',deletion_due_at=$2,updated_at=now() WHERE id=$1",[accountId,due]);
  await client.execute("UPDATE account_session SET revoked_at=now() WHERE account_id=$1 AND revoked_at IS NULL",[accountId]);
  const manifest=await client.execute<{id:string}>("INSERT INTO deletion_manifest(account_id,placeholder,status,due_at) VALUES($1,'DELETED_USER_'||lpad(nextval('deleted_user_number')::text,6,'0'),'PENDING',$2) RETURNING id",[accountId,due]);
  await appendAudit(client,{actorId:accountId,action:"account.deletion_requested",targetType:"account",targetId:accountId,domain:"privacy",sensitive:true});
  await appendDomainEvent(client,{eventType:"privacy.account.deletion_requested.v1",aggregateType:"deletion_manifest",aggregateId:manifest.rows[0].id,payload:{accountId,dueAt:due.toISOString()}});
  return{dueAt:due.toISOString()};
});}

export async function queueDeletionReminders(){return withTransaction(async client=>{const due=await client.execute<{id:string;account_id:string;due_at:Date}>("SELECT id,account_id,due_at FROM deletion_manifest WHERE status='PENDING' AND reminder_sent_at IS NULL AND due_at>now() AND due_at<=now()+interval '1 day' FOR UPDATE SKIP LOCKED LIMIT 100");for(const item of due.rows){await appendDomainEvent(client,{eventType:"privacy.account.deletion_reminder.v1",aggregateType:"deletion_manifest",aggregateId:item.id,payload:{accountId:item.account_id,dueAt:item.due_at.toISOString()}});await client.execute("UPDATE deletion_manifest SET reminder_sent_at=now() WHERE id=$1",[item.id]);}return{queued:due.rowCount??0};});}

export async function finalizeDueDeletions(){return withTransaction(async client=>{
  const due=await client.execute<{id:string;account_id:string;placeholder:string;email_normalized:string}>(`SELECT manifest.id,manifest.account_id,manifest.placeholder,account.email_normalized FROM deletion_manifest AS manifest JOIN account ON account.id=manifest.account_id WHERE manifest.status='PENDING' AND manifest.due_at<=now() FOR UPDATE OF manifest,account SKIP LOCKED LIMIT 25`);
  for(const item of due.rows){
    const media=await client.execute<{id:string;object_key:string}>("SELECT media.id,media.object_key FROM media_object AS media LEFT JOIN support_ticket AS ticket ON media.owner_type='TICKET' AND media.owner_id=ticket.id WHERE media.deleted_at IS NULL AND NOT media.legal_hold AND ((media.owner_type='ACCOUNT_UPLOAD' AND media.owner_id=$1) OR ticket.account_id=$1) FOR UPDATE OF media",[item.account_id]);
    for(const object of media.rows){await deleteObjectKey(object.object_key);await client.execute("UPDATE media_object SET deleted_at=now(),deletion_reason='ACCOUNT_DEIDENTIFICATION',object_key='purged/'||id,verified_mime='application/x-deleted',byte_size=1,sha256='deleted',alt_en=NULL,alt_ar=NULL WHERE id=$1",[object.id]);}
    await client.execute("DELETE FROM account_address WHERE account_id=$1",[item.account_id]);
    await client.execute("DELETE FROM phone_verification_request WHERE account_id=$1",[item.account_id]);
    await client.execute("DELETE FROM auth_token WHERE account_id=$1",[item.account_id]);
    await client.execute("DELETE FROM pending_login WHERE account_id=$1",[item.account_id]);
    await client.execute("DELETE FROM webauthn_challenge WHERE account_id=$1",[item.account_id]);
    await client.execute("DELETE FROM account_session WHERE account_id=$1",[item.account_id]);
    await client.execute("DELETE FROM webauthn_credential WHERE account_id=$1",[item.account_id]);
    await client.execute("DELETE FROM recovery_secret WHERE account_id=$1",[item.account_id]);
    await client.execute("UPDATE ticket_message SET body='[customer content removed during account de-identification]' WHERE author_id=$1",[item.account_id]);
    await client.execute("UPDATE support_ticket SET subject='Account support history' WHERE account_id=$1",[item.account_id]);
    await client.execute("UPDATE shop_order SET recipient_snapshot=jsonb_build_object('name',$2::text,'phone',NULL::text),delivery_snapshot=delivery_snapshot-'address'-'notes'-'instructions' WHERE account_id=$1",[item.account_id,item.placeholder]);
    await client.execute("UPDATE shipment SET delivery_pin_hash=NULL,pin_expires_at=NULL WHERE order_id IN(SELECT id FROM shop_order WHERE account_id=$1)",[item.account_id]);
    await client.execute("UPDATE notification SET subject_snapshot=NULL,body_snapshot=NULL,provider_message_id=NULL,failure_code=CASE WHEN failure_code IS NULL THEN NULL ELSE 'REDACTED' END WHERE recipient_id=$1",[item.account_id]);
    await client.execute("DELETE FROM outbound_secret WHERE event_id IN(SELECT id FROM domain_event_outbox WHERE payload->>'accountId'=$1::text)",[item.account_id]);
    await client.execute("UPDATE account SET email_normalized=$2||'@deleted.invalid',pending_email_normalized=NULL,password_hash='DELETED',display_name=$2,phone_e164=NULL,email_verified_at=NULL,phone_verified_at=NULL,status='DELETED',deletion_due_at=NULL,updated_at=now() WHERE id=$1",[item.account_id,item.placeholder]);
    await queueSecureDelivery(client,{eventType:"privacy.account.deletion_finalized.v1",aggregateType:"deletion_manifest",aggregateId:item.id,accountId:item.account_id,channel:"EMAIL",destination:item.email_normalized,token:"",expiresAt:new Date(Date.now()+24*60*60*1000),payload:{placeholder:item.placeholder}});
    await client.execute("UPDATE deletion_manifest SET status='APPLIED',applied_at=now(),details=$2::jsonb WHERE id=$1",[item.id,JSON.stringify({mediaPurged:media.rowCount??0,restorePolicy:"replay_manifest_before_serve"})]);
  }
  return{finalized:due.rowCount??0};
});}

export async function purgeClosedAttachments(){return withTransaction(async client=>{
  const due=await client.execute<{id:string;object_key:string}>(`SELECT media.id,media.object_key FROM media_object AS media JOIN support_ticket AS ticket ON media.owner_type='TICKET' AND media.owner_id=ticket.id WHERE ticket.status='CLOSED' AND ticket.attachment_purge_at<=now() AND media.deleted_at IS NULL AND NOT media.legal_hold FOR UPDATE OF media,ticket SKIP LOCKED LIMIT 100`);
  for(const object of due.rows){await deleteObjectKey(object.object_key);await client.execute("UPDATE media_object SET deleted_at=now(),deletion_reason='SUPPORT_RETENTION',object_key='purged/'||id,verified_mime='application/x-deleted',byte_size=1,sha256='deleted',alt_en=NULL,alt_ar=NULL WHERE id=$1",[object.id]);}
  return{purged:due.rowCount??0};
});}

export async function purgeExpiredDeliveryProofs(){return withTransaction(async client=>{const due=await client.execute<{attempt_id:string;media_id:string;object_key:string}>(`SELECT attempt.id AS attempt_id,media.id AS media_id,media.object_key FROM delivery_attempt AS attempt JOIN media_object AS media ON media.id=attempt.proof_media_id WHERE attempt.proof_purge_at<=now() AND media.deleted_at IS NULL AND NOT media.legal_hold FOR UPDATE OF attempt,media SKIP LOCKED LIMIT 100`);for(const proof of due.rows){await deleteObjectKey(proof.object_key);await client.execute("UPDATE media_object SET deleted_at=now(),deletion_reason='DELIVERY_PROOF_RETENTION',object_key='purged/'||id,verified_mime='application/x-deleted',byte_size=1,sha256='deleted',alt_en=NULL,alt_ar=NULL WHERE id=$1",[proof.media_id]);await client.execute("UPDATE delivery_attempt SET location_snapshot=NULL,proof_purge_at=NULL WHERE id=$1",[proof.attempt_id]);}return{purged:due.rowCount??0};});}
