"use client";
import { useRouter } from "next/navigation";
import { useApiAction } from "@/components/use-api-action";
import { requestApi } from "@/lib/client-api";
export type ReferralOperation = { id: string; code: string; active: boolean; custom: boolean; owner_public_id: string; reward_count: number; completed_fils: string };
export type ReferralOperationsData = { codes: ReferralOperation[]; rewards: { id: string; status: string; reward_fils: string; recovery_required: boolean; status_reason: string | null; referrer_public_id: string; order_public_id: string }[] };
export function ReferralOperations({ referrals }: { referrals: ReferralOperationsData }) {
  const router = useRouter();
  const { pending, perform, message, live } = useApiAction();
  async function change(body: unknown) { const completed = await perform(() => requestApi("/api/v1/admin/referrals", { method: "PATCH", body }).then(() => undefined), { en: "Referral state updated.", ar: "تم تحديث حالة الإحالة." }); if (completed) router.refresh(); }
  return <section id="referrals"><h2>Referrals / الإحالات</h2><p>Search is available through the referrals API. Customer identities are represented only by public IDs here.</p><p aria-live={live}>{message}</p><div className="list">{referrals.codes.length ? referrals.codes.map((entry) => <article key={entry.id}><div><strong>{entry.code}</strong><small>{entry.owner_public_id} · {entry.custom ? "custom" : "random"} · {entry.active ? "active" : "disabled"}</small></div><span>{entry.reward_count} rewards · {(Number(entry.completed_fils) / 1000).toFixed(3)} JOD completed</span>{entry.active ? <form onSubmit={(event) => { event.preventDefault(); const reason = String(new FormData(event.currentTarget).get("reason") ?? ""); void change({ action: "DISABLE_CODE", codeId: entry.id, reason }); }}><input name="reason" required placeholder="Reason for disable/invalidation" /><button className="secondary" disabled={pending}>Disable and invalidate unlocked referrals</button></form> : null}</article>) : <p>No referral codes yet.</p>}</div><h3>Reward review / مراجعة المكافآت</h3><div className="list">{referrals.rewards.length ? referrals.rewards.map((reward) => <article key={reward.id}><div><strong>{reward.status} · {(Number(reward.reward_fils) / 1000).toFixed(3)} JOD</strong><small>{reward.referrer_public_id} · {reward.order_public_id}</small></div><span>{reward.recovery_required ? "Manual Finance recovery required" : reward.status_reason ?? "No active flag"}</span>{!["REJECTED", "REVOKED"].includes(reward.status) ? <form onSubmit={(event) => { event.preventDefault(); const reason = String(new FormData(event.currentTarget).get("reason") ?? ""); void change({ action: "INVALIDATE_REWARD", rewardId: reward.id, reason }); }}><input name="reason" required placeholder="Fraud/refund reason" /><button className="secondary" disabled={pending}>Invalidate, freeze or recover</button></form> : null}</article>) : <p>No referral rewards yet.</p>}</div></section>;
}
