import {z} from "zod";import {withDatabaseClient,withTransaction} from "@/lib/db/client";import {appendAudit} from "@/lib/audit/service";
const windowInput=z.object({weekday:z.number().int().min(0).max(6),startsAt:z.string().regex(/^\d{2}:\d{2}$/),endsAt:z.string().regex(/^\d{2}:\d{2}$/),capacity:z.number().int().min(1)});
const zoneInput=z.object({nameEn:z.string().min(2),nameAr:z.string().min(2),feeFils:z.number().int().min(0),etaMinDays:z.number().int().min(0),etaMaxDays:z.number().int().min(0),policyReviewed:z.boolean(),windows:z.array(windowInput).min(1)}).refine(value=>value.etaMaxDays>=value.etaMinDays);
export async function listZones(){return withDatabaseClient(async client=>(await client.query(`SELECT zone.id,zone.name_en,zone.name_ar,zone.fee_fils,zone.eta_min_days,zone.eta_max_days,zone.active,zone.policy_reviewed,COALESCE(jsonb_agg(jsonb_build_object('id',delivery_slot.id,'weekday',delivery_slot.weekday,'startsAt',delivery_slot.starts_at,'endsAt',delivery_slot.ends_at,'capacity',delivery_slot.capacity)) FILTER(WHERE delivery_slot.id IS NOT NULL),'[]') AS windows FROM delivery_zone AS zone LEFT JOIN delivery_window AS delivery_slot ON delivery_slot.zone_id=zone.id AND delivery_slot.active GROUP BY zone.id ORDER BY zone.name_en`)).rows);}
export async function createZone(raw:unknown,actorId:string){const input=zoneInput.parse(raw);return withTransaction(async client=>{const result=await client.query<{id:string}>("INSERT INTO delivery_zone(name_en,name_ar,fee_fils,eta_min_days,eta_max_days,policy_reviewed) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[input.nameEn,input.nameAr,input.feeFils,input.etaMinDays,input.etaMaxDays,input.policyReviewed]);for(const window of input.windows)await client.query("INSERT INTO delivery_window(zone_id,weekday,starts_at,ends_at,capacity) VALUES($1,$2,$3,$4,$5)",[result.rows[0].id,window.weekday,window.startsAt,window.endsAt,window.capacity]);await appendAudit(client,{actorId,action:'delivery.zone.created',targetType:'delivery_zone',targetId:result.rows[0].id,domain:'delivery',after:input});return result.rows[0];});}
const termsInput=z.object({kind:z.enum(['TERMS','PRIVACY','COOKIES']),version:z.string().min(1),titleEn:z.string().min(2),bodyEn:z.string().min(10),titleAr:z.string().min(2),bodyAr:z.string().min(10),publish:z.boolean()});
export async function publishTerms(raw:unknown,actorId:string){const input=termsInput.parse(raw);return withTransaction(async client=>{const crypto=await import('node:crypto');const rows=[];for(const language of ['en','ar'] as const){const title=language==='en'?input.titleEn:input.titleAr;const body=language==='en'?input.bodyEn:input.bodyAr;const contentHash=crypto.createHash('sha256').update(`${title}\n${body}`).digest('hex');rows.push((await client.query<{id:string}>("INSERT INTO terms_document(kind,version,language,title,body,content_hash,published_at) VALUES($1,$2,$3,$4,$5,$6,CASE WHEN $7 THEN now() END) RETURNING id",[input.kind,input.version,language,title,body,contentHash,input.publish])).rows[0]);}await appendAudit(client,{actorId,action:'terms.version.created',targetType:'terms_document',targetId:input.version,domain:'terms',after:{kind:input.kind,version:input.version,published:input.publish}});return rows;});}
export async function latestDocument(kind:'TERMS'|'PRIVACY'|'COOKIES',language:'en'|'ar'='en'){return withDatabaseClient(async client=>(await client.query<{id:string;version:string;title:string;body:string}>("SELECT id,version,title,body FROM terms_document WHERE kind=$1 AND language=$2 AND published_at IS NOT NULL ORDER BY published_at DESC LIMIT 1",[kind,language])).rows[0]??null);}
export async function latestTerms(language:'en'|'ar'='en'){return latestDocument('TERMS',language);}
export async function listPickupLocations(){return withDatabaseClient(async client=>(await client.query("SELECT id,name_en,name_ar,address,hours FROM pickup_location WHERE active ORDER BY name_en")).rows);}
export async function createPickupLocation(input:{nameEn:string;nameAr:string;address:Record<string,unknown>;hours:Record<string,unknown>},actorId:string){return withTransaction(async client=>{const result=await client.query<{id:string}>("INSERT INTO pickup_location(name_en,name_ar,address,hours) VALUES($1,$2,$3::jsonb,$4::jsonb) RETURNING id",[input.nameEn,input.nameAr,JSON.stringify(input.address),JSON.stringify(input.hours)]);await appendAudit(client,{actorId,action:'pickup.created',targetType:'pickup_location',targetId:result.rows[0].id,domain:'delivery',after:input});return result.rows[0];});}
